name: Check
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read
on:
  pull_request:
    # On any pull requests to $default-branch
    branches: ['main']
jobs:
  terraform:
    name: "Terraform"
    uses: ankushjha-aj/terraform-worflow/.github/workflows/terraform-check.yaml@main
    secrets:
      GH_INFRA_PAT: ${{ secrets.ANKUSH_GH_PAT }}
      role-to-assume: ""
      role-session-name: ""
